### PR TITLE
Approved property in dashboard#37

### PR DESCRIPTION
**Pull request by adamhundley**
User property index page
  * user can view approved properties
  * styled a user viewing their properties
  * Property amenitizer PORO created to assign amenity object to properties
  * adjusted user dashboard navbar
  * need to implement update action
  * need to implement destroy action
  * many other small things

### CODE REVIEW

**Comment by adamhundley** [comment]
Hey dudes @natevenn @Salvi6God I am doing a PR in order to get this stuff up. Still got some work but it's working now.

**Comment by adamhundley** [comment]
@natevenn @Salvi6God don't merge yet. fixing tests

**Comment by adamhundley** [comment]
@Salvi6God should be good now. I also fixed the "list my pad!" problem

**Comment by natevenn** [comment]
Looks great Adam. Its a lot of new code. We should try and push smaller bits of code. Im guilty of the same thing. Nice work

**Pull request merged**
