### PR TITLE
Seed properties and users

### PR DESCRIPTION
**Pull request by natevenn**
Create seed class with generator methods for user_admin, properties, and amenities. 
@adamhundley @Salvi6God I commented out the little owl seed code but its still there if we want it later

### CODE REVIEW

**Comment by adamhundley** [comment]
This all looks good to me @natevenn Any change we can go ahead and generate the 3 property_types and a few regular users?

**Comment by natevenn** [comment]
@adamhundley yes I just wanted to get this pushed and merged and then I still need to add both property-types and images

**Comment by natevenn** [comment]
I went ahead and added the property_type associations with property and method generator for property_types

**Comment by Salvi6God** [comment]
It looks ready to merge guys!

**Pull request merged**
